blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (PostCreateView, PostDeleteView, PostDetailView,
                        PostListView, PostUpdateView)

app_name = BlogConfig.name


urlpatterns = [

    path("postdetails/<int:pk>/", PostDetailView.as_view(), name="post_details"),
    path("postcreate/", PostCreateView.as_view(), name="post_create"),
    path("postupdate/<int:pk>/", PostUpdateView.as_view(), name="post_update"),
    path("postdelete/<int:pk>/", PostDeleteView.as_view(), name="post_delete"),
    path("", PostListView.as_view(), name="post_list")]
    # path("", cache_page(60)(PostListView.as_view()), name="post_list")]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("admin/", admin.site.urls),
    path("", include("mail.urls", namespace="mail")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {"null": True, "blank": True}


class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name="Заголовок")
    body = models.TextField(verbose_name="Содержимое")
    preview = models.ImageField(upload_to='new_images', verbose_name="изображение", blank=True, null=True)
    created_at = models.DateField(verbose_name="Дата создания", auto_now=True)
    published = models.BooleanField(default=True, verbose_name="Опубликован")
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        verbose_name="Автор",
        **NULLABLE
    )
    view_count = models.PositiveIntegerField(default=0, verbose_name="Счётчик просмотров")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ("created_at",)

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from blog.models import Post


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ("title", "body", "preview")
    success_url = reverse_lazy("blog:post_list")

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class PostListView(ListView):
    model = Post


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy("blog:post_list")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if user != self.object.owner:
            raise Http404("Вы можете удалить только свои посты")
        return self.object


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ("title", "body", "preview")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser or user != self.object.owner:
            raise Http404("Вы можете редактировать только свои посты")
        return self.object

    def get_success_url(self):
        return reverse("blog:post_details", args=[self.kwargs.get("pk")])


def published_activity(request, pk):
    post_item = get_object_or_404(Post, pk=pk)
    if post_item.published:
        post_item.published = False
    else:
        post_item.published = True
    post_item.save()
    return redirect(reverse_lazy("blog:post_list"))

blog/templates/blog/post_confirm_dalete.html
{% extends 'mail/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <form method="post" enctype="multipart/form-data">
                 {% csrf_token %}
                 <p>Точно вы хотите удалить {{object.title}} ?</p>
                  <button type="submit" class="btn btn-primary">
                  Подтвердить
                  </button>
                  <a class="btn btn-success" href="{% url 'blog:post_list' %}" role='button'>
                  Отменить </a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'mail/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <form method="post" enctype="multipart/form-data">
                 {% csrf_token %}
                 <p>Точно вы хотите удалить {{object.title}} ?</p>
                  <button type="submit" class="btn btn-primary">
                  Подтвердить
                  </button>
                  <a class="btn btn-success" href="{% url 'blog:post_list' %}" role='button'>
                  Отменить </a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'mail/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                 <img src="{{object.preview|media_filter1}}" alt='Object Image' class='img-fluid'>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li> Создано: {{ object.created_at }}</li>
                        <li> Текст: {{ object.body }}</li></ul>
                    <p class = 'card-text'> Просмотров: {{object.view_count}} </p>

                </div>
            </div>
        </div>
    </div>
<div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'mail/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <form method="post" enctype="multipart/form-data">
                 {% csrf_token %}
                  {{ form.as_p}}
                  <button type="submit" class="btn btn-primary">
                    {% if object %}
                      Сохранить
                      {% else %}
                      Создать
                      {% endif %}
                  </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'mail/base.html' %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-4">
            {% for object in object_list %}
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                   <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li> Дата создания: {{ object.created_at }}</li>
                        <li> Текст: {{ object.body|slice:300 }}</li></ul>
                </div>
                <a class="p-2 btn btn-outline-primary" href='{% url "blog:post_details" object.pk %}'>Посмотреть </a>
                <a class="p-2 btn btn-outline-primary" href='{% url "blog:post_update" object.pk %}'>Редактировать </a>
                <a class="p-2 btn btn-outline-primary" href='{% url "blog:post_delete" object.pk %}'>Удалить </a>

            {% endfor %}

        </div>
<div>
             <a class="p-2 btn btn-outline-primary" href='{% url "blog:post_create" %}'>Создать пост </a></div>
         </div>
   </div>
</div>
{% endblock %}