blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (PostCreateView, PostDeleteView, PostDetailView,
                        PostListView, PostUpdateView)

app_name = BlogConfig.name


urlpatterns = [

    path("postdetails/<int:pk>/", PostDetailView.as_view(), name="post_details"),
    path("postcreate/", PostCreateView.as_view(), name="post_create"),
    path("postupdate/<int:pk>/", PostUpdateView.as_view(), name="post_update"),
    path("postdelete/<int:pk>/", PostDeleteView.as_view(), name="post_delete"),
    path("", PostListView.as_view(), name="post_list")]
    # path("", cache_page(60)(PostListView.as_view()), name="post_list")]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("admin/", admin.site.urls),
    path("", include("mail.urls", namespace="mail")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mail/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from mail.apps import MailConfig
from mail.views import (ClientCreateView, ClientDeleteView, ClientListView,
                        ClientUpdateView, MailAttemptListView,
                        MailingCreateView, MailingDeleteView,
                        MailingDetailView, MailingListView, MailingUpdateView,
                        MainPageView, MessageCreateView, MessageListView, ClientDetailView, toggle_activity_status)


app_name = MailConfig.name


urlpatterns = [
    path("mainpage/", cache_page(60)(MainPageView.as_view()), name="main_page"),
    path("mailingdetails/<int:pk>/", MailingDetailView.as_view(), name="mailing_details"),
    path("mailingcreate/", MailingCreateView.as_view(), name="mailing_create"),
    path("mailingupdate/<int:pk>/", MailingUpdateView.as_view(), name="mailing_update"),
    path("mailingdelete/<int:pk>/", MailingDeleteView.as_view(), name="mailing_delete"),
    path("messagelist/", MessageListView.as_view(), name="message_list"),
    path("messagecreate/", MessageCreateView.as_view(), name="message_create"),
    path("mailattemptlist/", MailAttemptListView.as_view(), name="mailattempt_list"),
    path("clientlist/", ClientListView.as_view(), name="client_list"),
    path("clientcreate/", ClientCreateView.as_view(), name="client_create"),
    path("clientdetails/<int:pk>/", ClientDetailView.as_view(), name="client_details"),
    path("clientupdate<int:pk>/", ClientUpdateView.as_view(), name="client_update"),
    path("clientdelete/<int:pk>/", ClientDeleteView.as_view(), name="client_delete"),
    path('mailingactivity/<int:pk>/', toggle_activity_status, name='mailing_activity'),
    path("", MailingListView.as_view(), name="mailing_list")]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (RegisterView, UserDetailView,
                         UserProfileView, restore_access, verify, UserListView, UserModerationView)

app_name = UsersConfig.name

urlpatterns = [

    path("logout/", LogoutView.as_view(), name="logout"),
    path("registration/", RegisterView.as_view(), name="register"),
    path("verify/<str:token>", verify, name="verify"),
    path("restore_access/", restore_access, name="restore"),
    path("user_detail/", UserDetailView.as_view(), name="user_detail"),
    path("user_update/", UserProfileView.as_view(), name="user_profile"),
    path("user_list/", UserListView.as_view(), name="user_list"),
    path("user_moderation/<int:pk>/", UserModerationView.as_view(), name="user_moderator"),
    path("", LoginView.as_view(template_name="users/login.html"), name="login"),
    # path('user_activity/<int:pk>/', blocked_users, name='users_block'),
]

users/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"null": True, "blank": True}


class User(AbstractUser):
    username = None
    first_name = models.CharField(max_length=100, verbose_name="Имя", **NULLABLE)
    last_name = models.CharField(max_length=100, verbose_name="Фамилия", **NULLABLE)
    phone_number = models.CharField(
        max_length=35, verbose_name="номер телефона", **NULLABLE)
    country = models.CharField(max_length=50, verbose_name="страна", **NULLABLE)
    email = models.EmailField(unique=True, verbose_name="Email")
    avatar = models.ImageField(
        upload_to="users/avatar/", verbose_name="Аватар", **NULLABLE
    )
    token = models.CharField(max_length=50, verbose_name="токен")
    # verify_code = models.UUIDField(
    #     default=uuid.uuid4, verbose_name="Код вeрификации", editable=False
    # )
    is_blocked = models.BooleanField(
        verbose_name="блокировка пользователя", default=False
    )
    comment = models.TextField(verbose_name="комментарий", **NULLABLE)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [
            ('block_users', 'Заблокuровать пользователя')]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from services import StyleFormMixin
from users.models import User


class RegistrationForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class RecoverForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ("email",)


class UserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ("email", "password", "first_name", "last_name", "avatar", "phone_number", "country")

    def __int__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password"].widget = forms.HiddenInput()


class UserModerationForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ("is_blocked",)

users/views.py
import random
import secrets

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.mail import send_mail
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, ListView

from config import settings
from users.forms import RecoverForm, RegistrationForm, UserForm, UserModerationForm
from users.models import User


# Create your views here.
class RegisterView(CreateView):
    model = User
    form_class = RegistrationForm

    def get_success_url(self):
        return reverse("users:login")

    def form_valid(self, form):
        user = form.save()
        token = secrets.token_hex(16)
        user.token = token
        user.is_active = False
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/verify/{token}"
        message = f"Привет, для подтверждения почты тебе нужно перейти по ссылке: {url}"
        send_mail("Верификация почты", message, settings.EMAIL_HOST_USER, [user.email])
        return super().form_valid(form)


def verify(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


def restore_access(request):
    if request.method == "POST":
        email = request.POST.get("email")
        user = User.objects.get(email=email)
        new_password = "".join([str(random.randint(0, 9)) for _ in range(8)])

        message = f"Ваш новый пароль : {new_password}"
        send_mail(
            "Восстановление доступа", message, settings.EMAIL_HOST_USER, [user.email]
        )
        user.set_password(new_password)
        user.save()
        return redirect(reverse("users:login"))
    else:
        form = RecoverForm
        context = {"form": form}
        return render(request, "users/restore.html", context)


class UserListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = User
    template_name = 'users/user_list.html'
    permission_required = ('users.view_user',)



    def get_queryset(self):
        customer_list = super().get_queryset()
        user = self.request.user
        if user.is_blocked == True:
            raise Http404("Вы заблокрованы")
        else:
            return customer_list


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User


class UserProfileView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'users/user_form1.html'
    form_class = UserForm
    success_url = reverse_lazy("users:user_list")

    def get_object(self, queryset=None):
        """редактируем текущего пользователя без передачи пк"""
        return self.request.user


# @login_required
# @permission_required('users.block_users')
# def blocked_users(request, pk):
#     user_one = get_object_or_404(User, pk=pk)
#     user_one.is_blocked = not user_one.is_blocked
#     # if user_one.is_bloсked:
#     #     user_one.is_bloсked = False
#     # else:
#     #     user_one.is_bloсked = True
#     user_one.save()
#     return redirect(reverse_lazy('users:user_list'))

class UserModerationView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = User
    form_class = UserModerationForm
    template_name = 'users/user_form2.html'
    permission_required = ('users.block_users',)

    def get_success_url(self):
        return reverse_lazy('users:user_list')

users/templates/users/login.html
{% extends 'mail/base.html' %}
{% block content %}

<div class="container">
     <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                          Вход
                          </div>
                    <div class="card-body">
                           {% csrf_token %}
                           {{ form.as_p }}
                       <button type="submit" class="btn btn-primary">
                           Войти
                        </button>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'users:restore' %}" class="btn btn-danger">Восстановить доступ</a>
                    </div>
                </div>
            </div>

     </form>
</div>
{% endblock %}

users/templates/users/restore.html
{% extends 'mail/base.html' %}
{% block content %}

<div class="container">
     <form class="row" method="post" enctype="multipart/form-data">
         {% csrf_token %}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                          Восстановление доступа
                          </div>
                    <div class="card-body">
                            {{ form }}
                       <button type="submit" class="btn btn-primary">
                           Отправить новый пароль
                        </button>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>

     </form>
</div>
{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends 'mail/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <form method="post" enctype="multipart/form-data">
                 {% csrf_token %}
                 <p>Точно вы хотите удалить {{object}} ?</p>
                  <button type="submit" class="btn btn-primary">
                  Подтвердить
                  </button>
                  <a class="btn btn-success" href="{% url 'mail:mailing_list' %}" role='button'>
                  Отменить </a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_datail.html
{% extends 'mail/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        Информация о рассылке: {{ object.name }}</h4>
                </div>
                <div class="card-body">
                      <table class="table">
                            <tr>
                                <td>Сообщение: {{ object.message}</td>
                             </tr>
                             <tr>
                                <td>ФИО: {{ object.first_lastname }}</td>
                             </tr>
                                <td> Телефон {{ object.phone_number }}</td>
                              <tr>
                                <td> Страна: {{ object.country }}</td>
                              </tr>
                             <tr>
                                <td>Емейл: {{ object.email }}</td>
                             </tr>
                            <tr>
                                <td>Аватар: {{ object.avatar | media_filter }}</td>
                             </tr>
                            <tr>
                                <td>Комментарий: {{ object.comment }}</td>
                             </tr>
                        </table>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'mail/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        Информация о клиенте:</h4>
                </div>
                <div class="card-body">
                      <table class="table">
                             <tr>
                                <td>Фамилия, Имя: {{ object.first_name }} {{ object.last_name }}</td>
                             </tr>
                                <td> Телефон {{ object.phone_number }}</td>
                              <tr>
                                <td> Страна: {{ object.country }}</td>
                              </tr>
                             <tr>
                                <td>Емейл: {{ object.email }}</td>
                             </tr>
                            <tr>
                                <td>Аватар: {{ object.avatar | media_filter }}</td>
                             </tr>
                            <tr>
                                <td>Комментарий: {{ object.comment }}</td>
                             </tr>
                        </table>
                </div>
               <a class="p-2 btn btn-outline-primary" href='{% url "users:user_update" object.pk %}'>Редактировать
               <a class="p-2 btn btn-outline-primary" href='{% url "users:user_delete" object.pk %}'>Удалить
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mail/base.html' %}
{% block content %}

<div class="container">
     <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                          Вход
                          </div>
                    <div class="card-body">
                           {% csrf_token %}
                           {{ form.as_p }}
                       <button type="submit" class="btn btn-primary">
                           Зарегистрироваться
                        </button>
                        <li> Вам нам почту будет отправлена ссылка. Перейдите по ссылке. </li>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>

     </form>
</div>
{% endblock %}

users/templates/users/user_form1.html
{% extends 'mail/base.html' %}
{% block content %}

<div class="container">
     <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                          Вход
                          </div>
                    <div class="card-body">
                           {% csrf_token %}
                           {{ form.as_p }}
                       <button type="submit" class="btn btn-primary">
                           Сохранить
                        </button>

                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>

     </form>
</div>
{% endblock %}

users/templates/users/user_form2.html
{% extends 'mail/base.html' %}
{% block content %}

<div class="container">
     <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                          Блокировка пользователя
                        <li>{{object.first_name}} {{object.last_name}} - {{object.email}};</li>
                          </div>
                    <div class="card-body">
                           {% csrf_token %}
                           {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                           Сохранить
                        </button>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>

     </form>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mail/base.html' %}

{% block content %}
{% if perms.users.view_user %}
<div class="container">
    <div class="col-12 mb-4">
        <h3 align="center" style="color:Black mb-4">Пользователи:</h3>
    </div>

    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header"></div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{object.first_name}} {{object.last_name}} - {{object.email}};</li>
                    </ul>
                    <br>
                    <div class="btn-group">
                        {% if not object.is_superuser and object != request.user %}
                        {% if object.is_blocked == True %}
                      <a class="p-2 btn btn-outline-danger" href='{% url "users:user_moderator" object.pk %}'>
                          Убрать блокировку </a>
                        {% else %}
                      <a class="p-2 btn btn-outline-success" href='{% url "users:user_moderator" object.pk %}'>
                          Заблокировать </a>
                         {% endif %}
                         {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}
{% endblock %}